//{"status":true,"data":{"categories":[{"ca
class UserData {
  bool? status;
  Data? data;
  UserData({this.status, this.data});
  factory UserData.fromJson(Map<String, dynamic> json) {
    return UserData(
      status: json['status'] as bool,
      data: Data.fromJson(json['data']),
    );
  }
}

class Data {
  List<Categories>? categories;
  List<Services>? services;
  List<Subservices>? subservices;
  Data({this.categories, this.services, this.subservices});
  factory Data.fromJson(dynamic json) {
    return Data(
      categories: List<Categories>.from(json["categories"].map((x) => Categories.fromJson(x))),
      services: List<Services>.from(
          json["services"].map((x) => Services.fromJson(x))),
      subservices: List<Subservices>.from(
          json["subservices"].map((x) => Subservices.fromJson(x))),
    );
  }
}

//"categoryId":"1","categoryName":"Selling Product OR Materials"
class Categories {
  String? categoryId;
  String? categoryName;
  Categories({this.categoryId, this.categoryName});

  factory Categories.fromJson(dynamic json) {
    return Categories(
      categoryId: json['categoryId'] as String,
      categoryName: json['categoryName'] as String,
    );
  }
}

//"services":[{"serviceId":"1","categoryId":"3","serviceName":"Electricals"},
class Services {
  String? serviceId;
  String? categoryId;
  String? serviceName;
  Services({this.serviceId, this.categoryId, this.serviceName});

  factory Services.fromJson(dynamic json) {
    return Services(
      serviceId: json['serviceId'] as String,
      categoryId: json['categoryId'] as String,
      serviceName: json['serviceName'] as String,
    );
  }
}

//"subservices":[{"subServiceId":"1","serviceId":"1","categoryId":"3","subServiceName":"AC"},
class Subservices {
  String? subServiceId;
  String? serviceId;
  String? categoryId;
  String? subServiceName;
  Subservices(
      {this.subServiceId,
      this.serviceId,
      this.categoryId,
      this.subServiceName});

  factory Subservices.fromJson(dynamic json) {
    return Subservices(
      subServiceId: json["subServiceId"],
      serviceId: json["serviceId"],
      categoryId: json["categoryId"],
      subServiceName: json["subServiceName"],
    );
  }
}





// class Autogenerated {
//   bool? status;
//   Data? data;

//   Autogenerated({this.status, this.data});

//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     status = json['status'];
//     data = json['data'] != null ? new Data.fromJson(json['data']) : null;
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['status'] = this.status;
//     if (this.data != null) {
//       data['data'] = this.data!.toJson();
//     }
//     return data;
//   }
// }

// class Data {
//   List<Categories>? categories;
//   List<Services>? services;
//   List<Subservices>? subservices;

//   Data({this.categories, this.services, this.subservices});

//   Data.fromJson(Map<String, dynamic> json) {
//     if (json['categories'] != null) {
//       categories = <Categories>[];
//       json['categories'].forEach((v) {
//         categories!.add(new Categories.fromJson(v));
//       });
//     }
//     if (json['services'] != null) {
//       services = <Services>[];
//       json['services'].forEach((v) {
//         services!.add(new Services.fromJson(v));
//       });
//     }
//     if (json['subservices'] != null) {
//       subservices = <Subservices>[];
//       json['subservices'].forEach((v) {
//         subservices!.add(new Subservices.fromJson(v));
//       });
//     }
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     if (this.categories != null) {
//       data['categories'] = this.categories!.map((v) => v.toJson()).toList();
//     }
//     if (this.services != null) {
//       data['services'] = this.services!.map((v) => v.toJson()).toList();
//     }
//     if (this.subservices != null) {
//       data['subservices'] = this.subservices!.map((v) => v.toJson()).toList();
//     }
//     return data;
//   }
// }

// class Categories {
//   String? categoryId;
//   String? categoryName;

//   Categories({this.categoryId, this.categoryName});

//   Categories.fromJson(Map<String, dynamic> json) {
//     categoryId = json['categoryId'];
//     categoryName = json['categoryName'];
//   }
// }

// class Services {
//   String? serviceId;
//   String? categoryId;
//   String? serviceName;

//   Services({this.serviceId, this.categoryId, this.serviceName});

//   Services.fromJson(Map<String, dynamic> json) {
//     serviceId = json['serviceId'];
//     categoryId = json['categoryId'];
//     serviceName = json['serviceName'];
//   }
// }

// class Subservices {
//   String? subServiceId;
//   String? serviceId;
//   String? categoryId;
//   String? subServiceName;

//   Subservices(
//       {this.subServiceId,
//       this.serviceId,
//       this.categoryId,
//       this.subServiceName});

//   Subservices.fromJson(Map<String, dynamic> json) {
//     subServiceId = json['subServiceId'];
//     serviceId = json['serviceId'];
//     categoryId = json['categoryId'];
//     subServiceName = json['subServiceName'];
//   }

// }
