name: hazrin
description: Hazrin project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  stacked: ^2.2.7
  page_transition: ^2.0.4
  json_annotation: 
  get_it: ^7.2.0
  injectable: ^1.5.0
  intl: ^0.17.0
  flutter_svg: ^0.23.0+1
  dotted_border: ^2.0.0+1
  google_maps_flutter: ^2.1.0
  just_audio: ^0.9.16
  audio_video_progress_bar: ^0.9.0
  photo_view: ^0.13.0
  chewie: ^1.2.2
  video_player: ^2.2.6
  video_thumbnail:
  path_provider:
  stacked_services: ^0.8.15
  pin_code_text_field: ^1.8.0
  linear_step_indicator: ^1.0.0+2
  timeline_tile: ^2.0.0
  custom_check_box: ^0.0.4
  animations: ^2.0.2
  dio: ^4.0.1
  image_picker: ^0.8.4+4
  syncfusion_flutter_sliders: ^19.3.48
  flutter_masked_text2: ^0.9.1
  shared_preferences:


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.4
  json_serializable: ^6.0.1




flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/

  fonts:
    - family: avertaStdBold
      fonts:
      - asset: assets/fonts/AvertaStd-Bold.ttf

    - family: avertaStdSemiBold
      fonts:
      - asset: assets/fonts/AvertaStd-Semibold.ttf

    - family: avertaDemoRegular
      fonts:
      - asset: assets/fonts/AvertaDemo-Regular.otf

    - family: interRegular
      fonts:
      - asset: assets/fonts/Inter-Regular.ttf


